const express = require("express");
const router = express.Router();
const app = express();
app.use(express.urlencoded());
// app.use(express.static(__dirname + "/assets"));
console.log("Router loaded");
const homeController = require("../controllers/home_controller");
router.get("/", homeController.home);
router.use("/users/", require("./users"));
router.post("/display", homeController.display);
router.use("/posts/", require("./posts"));
module.exports = router;
